on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hkk hello
    steps:
    - name: Hello world action step
      id: KuniakiHelloScript
      uses: k-hamamoto-cre/github_action_sample@master
      with:
        who-to-greet: 'KuniHama'
    # Use the output from the `hello` step
    - name: Get the output time hamamoto
      run: echo "The time was ${{ steps.hello.outputs.time }}"