on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: helloa
      uses: k-hamamoto-cre/github_action_sample@master
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time hama
      run: echo "The time was ${{ steps.helloa.outputs.time }}"